development: &db
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: tb-baseline-development
  pool: 5
  username: root
  password:
  xa: false
  socket: /tmp/mysql.sock

test:
  <<: *db
  database: tb-baseline-test
